### ISSUE TITLE
Implement Rule S5.8 (co_await)

### ISSUE THREAD

**Issue by nobugs-hare** [node-dot-cpp/memory-safe-cpp#1]

**Comment by marcosbracco** [comment]
Implementing this rule as it should be, would require doing path flow analysis, and that is non trivial thing. We will have to make it anyway when reimplementing rule 5 in total. So I am pushing as a workaround, to always warning about naked_ptr and references inside coroutines.

**Comment by marcosbracco** [comment]
Updated to never allow naked_ptr or references variables and/or parameters on coroutines.
In the body of coroutines, naked_ptr and references are allowed inside temporary expressions, but not as named variables or function parameters.

**Comment by nobugs-hare** [comment]
It would be really nice to be a bit less restrictive while still avoiding flow analysis:
- naked_ptr<> are prohibited _as long as their scope contains co_await_

In other words:

```
{
naked_ptr<X> x = ...;//ERROR
co_await whatever(); 
}
```

but 

```
{
{
naked_ptr<X> x = ...;//Ok, as scope of x doesn't overlap with co_await
}
co_await whatever(); 
}
```

and

```
{
co_await whatever(); 
naked_ptr<X> x = ...;//Ok, as scope of x doesn't overlap with co_await
}
```

**Comment by marcosbracco** [comment]
Pushed to 'develop' a fix to implement that.

**Comment by marcosbracco** [comment]
Also same behaviour around 'co_yield'
