### ISSUE TITLE
Create soft_ptr_stub<>

### ISSUE THREAD

**Issue by nobugs-hare** [node-dot-cpp/memory-safe-cpp#11]
soft_ptr_stub<> is intended to be used when implementing collections. 

it is similar to soft_ptr<> (in particular, it can be used to create soft_ptr<> out of it) - but does not cause keeping back references (to improve performance). NB: when creating soft_ptr<> out of soft_ptr_stub<> - created soft_ptr<> MUST be back-referenced.

MUST NOT be used outside of collection implementations.

**Comment by divanchykhin** [comment]
Correction:
To make (re)construction of soft_ptr<> from soft_ptr_stub<> possible while keeping  internals of soft_ptr_stub<> simple, a concept of zero offset is used (that is, in terms of soft_ptr<>, dereferencable and allocated pointers  are the same).
Thus, 
 - soft_ptr_stub<> becomes soft_ptr_with_zero_offset<> with a single pointer inside;
 - soft_ptr_with_zero_offset<T> can be obtained from an owning_ptr<T> or from another soft_ptr_with_zero_offset<T>;
 - soft_ptr_with_zero_offset<T> can be converted to soft_ptr<T>
