### ISSUE TITLE
Implement safe nodecpp::unordered_map<>

### ISSUE THREAD

**Issue by nobugs-hare** [node-dot-cpp/memory-safe-cpp#12]
Depends on #11 

Suggested to base implementation on eastl . 

Suggested approach:
- take eastl1s unordered_map<>; **whenever forking eastl file, make sure to make a comment within the forked file, with BOTH eastl version number, AND github's commit ID of the file**
- change applicable pointers to owning ones
- change all other pointers to soft_ptr_stub<>s
- based on usual iterator, implement safe_iterator
- implement functions returning both iterators and safe iterators out of the collection; functions returning safe iterators should have _safe suffix (example: find_safe());
NB: zeroing of pointer within destructor will be done by destructor of owning_ptr<>(s).

**Comment by marcosbracco** [comment]
Done at 8148c201
