### ISSUE TITLE
Implement safe nodecpp::vector

### ISSUE THREAD

**Issue by nobugs-hare** [node-dot-cpp/memory-safe-cpp#16]
Depends on #15 

Suggested to base implementation on eastl .

Suggested approach:
- take eastl's vector<>; **whenever forking eastl file, make sure to make a comment within the forked file, with BOTH eastl version number, AND github's commit ID of the file**
- change pointer to vector data to an owning one
- based on usual iterator, implement safe_iterator (using safe_ptr_range<>)
- implement functions returning both iterators and safe iterators out of the collection; functions returning safe iterators should have _safe suffix (example: find_safe());
- NB: zeroing of pointer within destructor will be done by destructor of owning_ptr<>(s).

**Comment by marcosbracco** [comment]
I am currently restricting vector element to be no-throw move ctor / assign.
There are two situations involving moves inside vector that require thinking about exceptions:
* At storage relocation, all elements are moved from one place to other. This case is simple, if element has nothrow move, use it, else use copy. If one element throws while copying, release everything, and vector will still be as it was before starting. Strong safety exception is granted.

* When one element is inserted/removed from a place _in the middle_ (other than back). Here the situation is more tricky, a lot of elements need to be moved (one by one) inside the storage, and if one copy constructor throws, then we end having a vector with one element in the middle that is in some kind of zoombie state. Basic exception guarranties here. The user most likely won't be able to continue using this vector instance.

I see 4 possible solutions to this issue:
1. The simplest and currently in place, T __must__ be no-throw move ctor/assign
2. Always copy the storage when insert/remove an element from the middle and T doesn't have no-throw move ctor/assign. This will make such operations slower but will provide strong exception guarranties.
3. Release everything (clear the vector). The user most likely won't be able to use it anyway.
4. Review a lot of code, and make a lot of tests to make sure that even if we get a broken object in the middle of the vector, it will not be a safety issue. Maybe zeroing the place or something like that. Not really sure now, will need to think about that.

Comments are welcome.

**Comment by nobugs-hare** [comment]
Thanks!

1. is ok for the time being; as soon as we'll see concrete cases which don't fall under this restriction - we'll be able to say which way to go.

**Comment by marcosbracco** [comment]
Done at 8148c201
