### ISSUE TITLE
Discuss about const refs to temporaries

### ISSUE THREAD

**Issue by marcosbracco** [node-dot-cpp/memory-safe-cpp#27]
From #8 

I believe no current rule covers this case (at least not explicitly):

`const int& func(const int& arg) {return arg;} const int& x = func(i + 1);`

Here the temporary at `i + 1` is life extended to create a const ref, and the variable `x` will point to a dangling reference.

Rule S5.2 assumes the returning ref at `func` has the same lifetime as its incoming argument reference, but this is not true. The argument may be a temporary with extended lifetime https://en.cppreference.com/w/cpp/language/reference_initialization#Lifetime_of_a_temporary

Currently checker implements a hack rule that prohibits initializing a reference variable from an expression that contains _cleanup_ (any lifetime extension or some other tricky stuff)
But I am not sure this cover all cases.

**Comment by nobugs-hare** [comment]
Are you 100% sure that this is a case for temporary (rather than simply copying a reference back -which should be possible and desirable as temporary *seems* unnecessary)? Can you ask about it (without referring to our code, just in terms of temporary being created or not) on StackOverflow?

**Comment by marcosbracco** [comment]
I will elaborate better, if there are still doubts then I will ask StackOverflow. When you do:

    const int& func(const int& arg) {return arg;}
    const int& x = func(i);

There is no problem. There are no temporary, and this is perfect valid code under checker.

When you do:

    const int& x = func(i + 1);

Then `i + 1` creates a temporary, then a const reference is bound to the temporary, and lifetime of the temporary is extended until the end of the full expression.

As a general case, when a function returns a value, such value can be passed by const reference to another function, then the potencial issue is generated (somtimes without even notice to the user).

    struct Some {};
    Some createSome() { return Some(); }
    const Some& readSomeByRef(const Some& ref) { return ref; }

    const Some& s = readSomeByRef(createSome());

Then `s` will be dangling, no doubt about it. And that may be tricky to spot.

When code like this is parsed, the AST gets an _special_ node `ExprWithCleanups` at the root of the initializer expression. Such node will take care of (generate the code for) destroying the temporary after the statement is finished. When checker finds such node inside an intializer is a sign of something potencially dangerous, and rejects such expression as a valid initializer for a reference.

**Comment by nobugs-hare** [comment]
Got it; my feeling is that your current implementation _seems_ to be ok (though MAY be overbroad); as a result, I suggest to:
- keep current implementation until/unless demonstrated overbroad (or false negatives are demonstrated)
- add a rule on prohibiting refs to temporaries.
