### ISSUE TITLE
Discuss [[nodecpp::may_extend_to_this]]

### ISSUE THREAD

**Issue by marcosbracco** [node-dot-cpp/memory-safe-cpp#29]
Review and discuss attribute `[[nodecpp::may_extend_to_this]]`

Change rules **S5.7** and **S5.8** to allow `[[nodecpp::may_extend_to_this]]` only to be used at library code interface or api, and only on `std::function` or _lambdas_ as currently is the only use case.
Split from #8

**Background:**

In the very early days this attribute was to be used with raw pointers and lambdas, but since now we have a clear division between stack (naked_ptr and naked_struct) and long term heap (owning_ptr and soft_ptr) for pointers, this attribute only remaining place is at lambdas.

For lambdas we don't have a clear way to tell its intended lifetime.

Lambda can be stack lived:

	find(v.begin(), b.end(),  [...](...) {...} );

Or it can be long time heap lived, when infra stores it for calling as event handler:

	clientSock->on(event::connect, [this]() { ... });

Both use cases need different set of rules under checker. The first may capture stack elements by reference while the second don't, and most important, the capture of 'this' on the second case must be carefully verified to be sure it won't be dangling by the time the lambda is called.
From **Rule S5.7** we assume that by-default lambas will be stack lived, and checker does it job acordingly.
When we need a lambda to be long lived, we must add the mark-up attribute `[[nodecpp::may_extend_to_this]]`. Checker will put harder checks on the caller side and special rules to ckeck the capture of `this`.

Now for most use cases, the _called_ side is at libray code and this is the end of the story. What is actually done with such lambda is responsability of library programmers.

But currently checker has some extra rules to allow the attribute to be used at user code (again most use cases from very early work using raw pointers).
Only interesting (exploratory) point still living is to allow user code to use `std::function` as safe.
The main idea was to allow user code to store `std::function` members on the heap, by controling what was assigned inside them and only allowing certain lambdas.

While this currently seems works fine, it may need more review before going into a definitive rule.

**Proposal:**
I suggest to change **[Rule S5.6]** and **[Rule S5.7]** (and swap their order) with the text below and remove all exploratory work from checker.

**[Rule S5.6]** Lambda is considered as an implicit _naked_struct_, captures may include local var references, _naked_ptrs_ and raw pointer `this`.

TEST CASES/ALLOW: `sort()` passing lamda with local vars captured by reference

**[Rule S5.7]** There is special parameter mark-up `[[nodecpp::may_extend_to_this]]` that may be applied to method parameter of type `std::function` or _lambda_ on library code api (or `[[nodecpp::memory_unsafe]]` marked code), AND means that the scope of marked-up parameter MAY be extended to `this` of called instance. If such a parameter is specified, then the scope of the captures MUST be equal-or-larger-than the scope of the called instance.

* When applied to parameter of type `std::function`, it means it can only be initialized with a lambda that verifies the mentioned retrictions.
* In the future, we MAY introduce other similar mark-up (`[[nodecpp::may_extend_to_a]]`?)
* TEST CASES/PROHIBIT: `this->on()` (which is marked as `[[nodecpp::may_extend_to_this]]`) passing lambda with local vars passed by reference
* TEST CASES/ALLOW: `this->on()` passing lambda with `this->members` captured by reference

**Comment by nobugs-hare** [comment]
ok, let's proceed
