### ISSUE TITLE
Implement Rule S9.1 (restrictions on uses of co_await)

### ISSUE THREAD

**Issue by nobugs-hare** [node-dot-cpp/memory-safe-cpp#3]

**Comment by marcosbracco** [comment]
I will be pushing a quick fix to this, that only allows temporaries awaitables. i.e.
`co_await af();` or `wait_for_all(af(), af2());` and does not allow creating variables of type awaitable for later co_await. i.e. `auto a = af(); co_await a;`

The most dificult part of allowing to create awaitable vars  is to make really sure that nobody `co_await` twice on the same var, as such thing will break. i.e. `auto a = af; co_await a; co_await a;`
Solving such problem is very dificult to our current state of analysis, and would take a big effort. Probably will be easier to solve when we can solve similar issue with `naked_ptr` and references being invalidated after a `co_await`
