### ISSUE TITLE
How checker deals with templates

### ISSUE THREAD

**Issue by marcosbracco** [node-dot-cpp/memory-safe-cpp#30]
I believe what follows below is an implementation detail not worth to mention on the Rules. But not really my desicion to make.

This involves **[Rule S5.4]** (about naked_ptr<> and references on the heap) **[Rule S1.4]** (about unions) and also **[Rule D2.1]** (about determinism and members intializers) 

With templates most of the time we can't really know if a class is valid or not until instantiation.

	template <class T>
	class MayBeBad {
		T t;
		MayBeBad(T t): t(t) {}
	};

	void func() { 

		int i = 42;
		typedef MayBeBad<int&> BadType;
		owning_ptr<BadType> bad = make_owning<BadType>(i);
	}

Unions can be dangerous even at temporaries:

	template <class T>
	union MayBeBad {
		int i;
		T ptr;
	};

	template<class T>
	struct UsesUnion {
		MayBeBad<T> U;

		UsesUnion(int ii)  { U.i = ii; }
		T get() const { return U.ptr; }
	};

	void func(int) { 

		typedef UsesUnion<int*> BadThing;
		func(*BadThing(42).get());
	}

Non-determinism can also be found with temporaries.

So, to be able to check all this cases, what checker actually do is to verify every variable declaration type, every function parameter type, and every temporary contructor, and analyze the actual instantiation of the type.
That is, once all the template parameters are known we check the type that is actually created.

Non-template clases are checked at their declaration (`class Some { ... };`), while template types are checked when used (at variable declaration or temporary creation). But this dual behaviour results in non-uniform error reporting and sometimes duplicate error messages, so maybe we should check everything the same way we check templates.

Below is error message from sample code above. Error message points to the temporary that triggers the error, and the 'note' lines have the stack to find the template that caused the problem. Still place for improvement but actually quite good for understanding the issue. 

	test.cpp:20:9: error: unsafe type at temporary expression [memory-safe-cpp]
	                func(*BadThing(42).get());
	                      ^
	test.cpp:6:5: note: (S1.4) raw pointers inside unions are prohibited
	                T ptr;
	                  ^
	test.cpp:11:15: note: member 'U' is not safe
	                MayBeBad<T> U;

**Comment by nobugs-hare** [comment]
But what is the issue we're trying to solve here? Just inconsistent error reporting between template and non-template? Or something else?

**Comment by marcosbracco** [comment]
@nobugs-hare  There is not an issue here, just wanted to share a little bit about internals, since this grew quite a bit since the first drafts, and wanted to be sure you are up to date with it. When you first try the tool (or show it so someone for the first time) this little detail can be a little of a surprise. Just closing it.
