### ISSUE TITLE
Determinism and array initialization

### ISSUE THREAD

**Issue by marcosbracco** [node-dot-cpp/memory-safe-cpp#31]
**[Rule D2]** Prohibiting uinitialized variables, including partially unitialized arrays

I believe that partially initialized arrays are not a determinism issues.

	int A[10] = {0};

Is a common idiom and the array is initialized to all zero.
If there is no enought elements in the initializer, the rest of the array is zeroed.

https://stackoverflow.com/questions/1920430/c-array-initialization

Also from the test cases: `X x;` if X is a class/struct can't be a determinism issue because of **[Rule D2.1]** requires all members to have default initializers.

### Proposed change:

**[Rule D2]** Prohibiting uinitialized variables, ~~including partially unitialized arrays~~

**TEST CASES/PROHIBIT:** `int x;` (in function), `int a[3] = {1,2};` (in function), ~~`X x;` (in function, if class X has non-constructed members AND has no constructor),~~ `int x1 : 8;` (in function, this is an uninitialized bit field)

**Comment by nobugs-hare** [comment]
Ok.
