### ISSUE TITLE
Add support for self-contained data types

### ISSUE THREAD

**Issue by divanchykhin** [node-dot-cpp/memory-safe-cpp#32]
A type is **self-contained**, if, after copying an object of that type, all references/pointers in its copy point to objects inside that copy.

Examples:

 - numericals;
 - owning pointer to an object of self-contained type;
 - strings;
 - data structures consisting of the above
 
Sufficient condition: no "magic 5" (c(d)tors) and all members are also self-contained.

Implementation: potentially can go along lines of adding an attribute or constexpr.

**Also**: respective rule should be added.

**Comment by marcosbracco** [comment]
See #34
This was replace by [[deep_const]], mostly the same but `owning_ptr<const T>` are only allowed.
