### ISSUE TITLE
Check that Hash and KeyEqual objects and respective paramenters are self-contained and their operator () is no-side-effect

### ISSUE THREAD

**Issue by divanchykhin** [node-dot-cpp/memory-safe-cpp#34]
This appears to be a sufficient condition for hash and checking-equality functions being deterministic.

Depends on issue #32 
Depends on issue #33 

**Also**: respective rule should be added.

**Comment by marcosbracco** [comment]
Been thinking this a while, and i believe those are not enought.


We also need some idea of _deep constness_ as already in discussion for `static const` objects.



	struct Key {

		struct Inner {
			int i = 0;
		}

		owning_ptr<Inner> inn;

		int& getI() const { return inn->i; }

		bool operator==(const Key& other) const { return inn->i == other.inn->i; }
	};


Here this class is **self-contained** and **no-side-effect** method, but equality may not be repetable, as value of `i` may be modified from outside.

So we also need somehow to state that if `class A` is _deep const_, then any piece of data reachable from a const instance `const A a;` will remain constant for the complete lifetime of `a`. This is something that raw pointers, `nullable_ptr`, `soft_ptr` and `owning_ptr` do not hold true.
In practice this is usually enforced by accessor methods:

		
		int& getI() { return inn->i; }
		const int& getI() const { return inn->i; }

but such thing is far from current checker capabilities.
So some simplifications will need to be done, and full analysis left for some future.


Also there is the following around `KeyEqual`

	struct KeyEqual {
		bool operator()( const Key& lhs, const Key& rhs ) const {
			if(&lfs == &rhs)
				return true;
			else if(lhs.getI() == 42)
				return false;
			else
				return lhs.getI() == rhs.getI();
		}
	};

Here the `unordered_map` will work normally for most keys, but some specific key values will never be found (and the map will look like leaking).
So we need to also verify that each key instance we insert, at least compares equal to a copy of itself.
As seen in the example, comparing with the same instance may return true, but after that the key may become imposible to find from an idetical copy.
But this has also issues:

* Key needs to be copy constructible. Currently Key may be a move only type.
* Runtime overhead, this check needs to create a copy of each key we try to insert.

So such check will probably need to have a switch to enable/disable it.

**Comment by marcosbracco** [comment]
As show in updated rules at 8148c201, it was created a `[[deep_const]]` attribute to apply to classes, [[no_side_effect]] attribute to apply to functions.
At instantiation of `unordered_map<Key, Value, Hash, KeyEqual>` we check: 
* `Key` must be *deep_const*
* `Value` can be any safe type
* `Hash` and `KeyEqual` must meet *deep_const* and have an `operator()` that meets *no_side_effect* requirements.

All of this should make that all hash computations and equality comparison fully deterministics.
It is still unknown how to deal with a equality function that does bad things like the  one on the previous comment. The solution proposed in the previous comment won't really work. On the current state, the library will not be affected by a bad coded `KeyEqual` so safety can't be compromised.
