### ISSUE TITLE
Proposal: split naked_ptr<> into C/C++ ("raw") pointers, and nullable_ptr<>

### ISSUE THREAD

**Issue by nobugs-hare** [node-dot-cpp/memory-safe-cpp#39]
_**REALLY IMPORTANT** - as of now, it is only a PROPOSAL, comments are still VERY welcome._

Previously, the idea was to allow only owning_ptr<T>, soft_ptr<T>, and naked_ptr<T> at app-level. However, it seems to cause quite a bit of unnecessary changes when porting from "usual" C++ (and unnecessary verbosity too). 

Therefore, it is proposed to:
- say that instead of naked_ptr<T> there are TWO separate pointer types: 
  + (almost) usual C/C++ pointers ("raw" pointers)
    * to ensure safety, we MUST guarantee that "raw" pointers are NOT nullable. In particular, things such as `T* p = nullptr;` `p = nullptr;` , and `void f(T* p=nullptr)` MUST be prohibited.
    * "raw" pointers can be obtained EITHER from owning_ptr<>/soft_ptr<>, OR as a pointer to an on-stack variable (as `T t; T* p = &t;`)
    * "raw" pointers MUST obey "don't extend scope" rules; in particular, `int* f() { int i; return &i;}` and `void f() { int i; int *p = &i; { int j; p = &j; } *p=0; }` MUST be prohibited by static checker (within Rule S5,1)
  + nullable_ptr<T>. Implementation-wise, it should more or less correspond to current implementation of naked_ptr<> (with an ability to construct it from "raw" pointer).
    * static-checker rules for nullable_ptr<T> are EXACTLY the same as that of for "raw" pointers (except for rules for nullptr); in particular:
      + unlike "raw" pointers: `nullable_ptr<T>* p = nullptr;` `p = nullptr;` , and `void f(nullable_ptr<T> p=nullptr)` are ok.
      + like "raw" pointers: nullable_ptr<T> MUST obey "don't extend scope" rules; in particular, `nullable_ptr<int> f() { int i; return &i;}` and `void f() { int i; nullable_ptr<int> p = &i; { int j; p = &j; } *p = 0; }` MUST be prohibited by static checker (within Rule S5,1)
- there SHOULD be a way to obtain T* from nullable_ptr<T> - but with a runtime check for it being non-null (and throwing an exception if it was null). Proposed way to do it - is via `nullable_cast<T*>(p)` where p is nullable_ptr<T>; for consistency/completeness, it is proposed to provide `nullable_cast<nullable_ptr<T>>(p)` where p is T*, but as we can implicitly construct T* from nullable_ptr<T>, it is NOT necessary to use it (and there are no runtime checks in such conversion).  

**IMPORTANT: IF we decide to implement it, Implementing this issue REQUIRES changing STATIC-CHECKS.md accordingly**

**Comment by marcosbracco** [comment]
I pushed an _experimental_ implementation with non-null raw pointer support to branch develop.
To enable raw pointer, command line argument `-raw-ptr` must be supplied to checker. This will disable rules S1.2 and S1.3 (dereference of raw pointers and raw pointer variables).
See `checker/test/regression/raw.cpp`

**Comment by marcosbracco** [comment]
@nobugs-hare  below is proposed change to rules S1, S1.2 and S1.3 to support non-null raw pointers. Please review.
edit: updated S1.2

* Not allowing to create pointers except in an allowed manner
  - **[Rule S1]** any (sub)expression which has a type of T* (or T&) is prohibited unless it is one of the following:
    + (sub)expressino is an assignment where the right side of (sub)expression is already a pointer/reference to T (or a child class of T).
    + or (sub)expression is a `dynamic_cast<>` 
      * NB: MOST of C-style casts, reinterpret_casts, and static_casts (formally - all such casts between different types) MUST be prohibited under generic **[Rule S1]**, but SHOULD be reported separately under **[Rule S1.1]**
    + or (sub)expression is a function call
      ~~* in practice, only unsafe functions can do it - but returning T* from `owning_ptr<T>`/`soft_ptr<T>`/`naked_ptr<T>` functions is necessary~~
    + ~~or (sub)expression is _nullptr_~~
    + or (sub)expression is _this_
    + or (sub)expression is dereferencing of a `nullable_ptr<T>`, `soft_ptr<T>`, or `owning_ptr<T>`
      ~~- dereferencing of raw pointers is prohibited - and SHOULD be diagnosed as a separate **[Rule S1.2]**~~
    + or (sub)expression is a variable or function paramenter of type T*
    + or (sub)expression is address of object `&i`
    ~~+ NB: taking a variable address ("&i") is not necessary (it is done via constructor of `naked_ptr<>`)~~
    + NB: Convertion of literals `nullptr` and `0` to `T*` are prohibited and SHOULD be diagnosed as a separate **[Rule S1.2]**
    + NB: dereferencing `*nullptr` is not allowed by languaje as `nullptr` is of type `nullptr_t` and doesn't have overload `operator*`. And implicit conversion from `nullptr_t` to any `T*` is prohibited by this rule.
    + TEST CASES/PROHIBIT: `(int*)p`, `p^p2`, `p+i`, `p[i]` (syntactic sugar for *(p+a) which is prohibited), `p1=p2=p+i`, `*nullptr`, `*p` (necessary to ensure nullptr safety)
    + TEST CASES/ALLOW: `dynamic_cast<X*>(p)`, `p=p2`, `p=np`, `p=sp`, `p=op`, `fp(p)`, `fp(np)`, `fp(sp)`, `fp(op)`, `&i`, `*np`, `*sp`, `*op`
  - **[Rule S1.1]** C-style casts, reinterpret_casts, and static_casts are prohibited. See NB in [Rule S1]. NB: if [Rule S1] is already enforced, this rule [Rule S1.1] (which effectively prohibits even casts from X* to X*) is NOT necessary to ensure safety, but significantly simplifies explaining and diagnostics.
    + **[Rule S1.1.1]** special casts, in particular `soft_ptr_static_cast<>`. are also prohibited in safe code 
    + TEST CASES/PROHIBIT: `(int*)p`, `static_cast<int*>(p)`, `reinterpret_cast<int*>(p)`, `soft_ptr_static_cast<X*>(p)`   
  - ~~**[Rule S1.2]** Separate diagnostics for dereferencing of raw pointers (see above)~~
    ~~+ TEST CASES/PROHIBIT: `*nullptr`, `*p`~~
  - **[Rule S1.2]** Separate diagnostics for converting `nullptr` or `0` to any raw pointer type (see above)
    + TEST CASES/PROHIBIT: `int* x = 0;`, `void fp(nullptr);`
  - **[Rule S1.3]** raw pointer variables (of type T*) and raw pointer function parameters MUST be initialized to non-null value. ~~. Developers should use `naked_ptr<>` instead. NB: this rule is NOT necessary to ensure safety, but [Rule S1] makes such variables perfectly useless (both calculating new values and dereferencing are prohibited on raw pointers) so it is better to prohibit them outright~~ NB: [Rule S1] already enforces that null values are not valid T* expressions.
    + NB: raw references are ok (we're ensuring that they're not null in the first place)
    + TEST CASES/PROHIBIT: `int* x;`
    + TEST CASES/ALLOW:`int* x = &i;`

**Comment by nobugs-hare** [comment]
looks good, but there is one question: how do we prohibit outright *nullptr = 123;?

**Comment by marcosbracco** [comment]
Added a note on rule S1.

`nullptr` is of type `nullptr_t` and it doesn't have overload `operator*`, so it can't be derefenced without previous (maybe implicit) convertion to some `T*`. And under **[Rule S1]** we are prohibiting such convertion. The same thing happends with literal `0`.

**Comment by nobugs-hare** [comment]
@marcosbracco sounds good, but just to be 100% sure, let's have a PROHIBIT test case on *nullptr = 123; _somewhere_.
