### ISSUE TITLE
Force await on awaitables others than nodecpp::awaitable

### ISSUE THREAD

**Issue by marcosbracco** [node-dot-cpp/memory-safe-cpp#41]
While rule **S9.1** work fine on `nodecpp::awaitable`, there are lot of other awaitables that are inline declared inside a function, and that that they must checked for `co_await`

For instance, include/nodecpp/socket_common.h, at line 676 aprox.

     auto a_write(Buffer& buff) {

          struct write_data_awaiter {
              bool await_ready() { ... }
              void await_suspend(std::experimental::coroutine_handle<> awaiting) { ... }

              auto await_resume() { ... }
          };
          return write_data_awaiter(*this, buff);
      }

We need to somehow explain to checker that what is returned by `a_write` must be `co_await` ed, and update **STATIC-CHECKS.md**
See also #24

**Comment by nobugs-hare** [comment]
What about adding a new function attribute (available ONLY in unsafe code), say, [[nodecpp::awaitable]]?

**Comment by marcosbracco** [comment]
New attribute [[nodecpp::awaitable]] applies to the awaitable class (ONLY in unsafe code).
