### ISSUE TITLE
Match STATIC-CHECKS.md against current implementation of static checker

### ISSUE THREAD

**Issue by nobugs-hare** [node-dot-cpp/memory-safe-cpp#8]
We need to:
a. Make sure that ALL the rules currently enforced by static checker, are listed in STATIC-CHECKS.md
b. Make sure that ALL the rules currently in STATIC-CHECKS.md, but NOT enforced by static checker, have their own issues.

**Comment by marcosbracco** [comment]
Under Rule S1 dereferencing of __this__ should be allowed.
Under Rule S6.1, clarify that MSVC-asm is understand by clang, and also reported.

**Comment by marcosbracco** [comment]
All pending parts have its own issues assigned
